publishing the error logs again

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -55,7 +55,12 @@ jobs:
           
           # apply provisioning profile
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+          if [ -f "$PP_PATH" ]; then
+            cp "$PP_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/
+          else
+            echo "Provisioning profile not found: $PP_PATH"
+            exit 1
+          fi
 
           # Create variables
           CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
